name=input("Enter your name: ")
phone_number=input("Enter your phone number: ")
result=len(name)
result=name.find("a")
result=name.rfind("q")
name=name.capitalize()
name=name.upper()
name=name.lower()
result=name.isdigit()
result=name.isalpha()
result=phone_number.count("-")
result=phone_number.replace("-","")
print(result)